/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Akademik;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 3cc
 */
public class CariMHS extends javax.swing.JFrame {
    public Connection conn;
    public Statement cn;
    public ResultSet rs;
    public PreparedStatement stmt;
    /**
     * Creates new form CariMK
     */
    public CariMHS() {
        initComponents();
    }

    private void koneksi() {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/akademik2322009","root","");
            cn = conn.createStatement();
            System.out.println("Koneksi dan statement berhasil dibuat!");
        }catch(SQLException e){
            /*JOptionPane.showMessageDialog(null, "Field " + field.getName() + 
                    " tidak boleh kurang dari satu!", 
                    "input tidak valid!", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Kesalahan koneksi atau pembuatan statement\n" + e.getMessage(),
                                            "Masalah Koneksi-Statement", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Kesalahan penggunaan driver\n" + e.getMessage(),
                                            "Masalah Driver", JOptionPane.ERROR_MESSAGE);
            System.exit(0); //harusnya nilainya 1
        }   
    }
    
    public void tampildata(){
        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("NIM");
        tabelnyo.addColumn("Nama Mahasiswa");
        tabelnyo.addColumn("Semester");
        try{
        koneksi();
        String sql = "Select * from mahasiswa_2322009 order by NIMMHS_2322009";
        rs = cn.executeQuery(sql);
        while(rs.next())
        {
        tabelnyo.addRow(new Object[]{
        rs.getString(1),
        rs.getString(2),
        rs.getInt(11)
        });
        }
        tblCariMK.setModel(tabelnyo);
        }catch (SQLException e){
        JOptionPane.showMessageDialog(null, "Ada Kesalahan");
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fdCariMK = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCariMK = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CARI NIM/NAMA MAHASISWA");

        fdCariMK.setName("Cari Mata Kuliah"); // NOI18N
        fdCariMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdCariMKActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fdCariMK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fdCariMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCariMK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCariMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCariMKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCariMK);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fdCariMKActionPerformed1() {
    // TODO add your handling code here:
        DefaultTableModel tabelnyo = new DefaultTableModel();
        tabelnyo.addColumn("NIM");
        tabelnyo.addColumn("NAMA MAHASISWA");
        tabelnyo.addColumn("SEMESTER");
        try{
        koneksi();
        String sql = "Select * from mahasiswa_2322009 where NIMMHS_2322009 ='" + fdCariMK.getText() + "' or " +
        "namaMHS_2322009 like '%" + fdCariMK.getText() + "%'";
        rs = cn.executeQuery(sql);
        while (rs.next()) {
        tabelnyo.addRow(new Object[]{
        rs.getString(1),
        rs.getString(2),
        rs.getInt(11)
        });
        }
        tblCariMK.setModel(tabelnyo);
        }catch (SQLException e){
        JOptionPane.showMessageDialog(null,"Terjadi Kesalahan " + e);
        }
        }
    
    private void fdCariMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdCariMKActionPerformed
        // TODO add your handling code here:
        fdCariMKActionPerformed1();
    }//GEN-LAST:event_fdCariMKActionPerformed

    private void tblCariMKMouseClicked1() {
        // TODO add your handling code here:
        int row;
        row=tblCariMK.getSelectedRow();
        if(EntriKRS.fdNIM != null || EntriKRS.fdNama != null || EntriKRS.fdSemester != null){
            EntriKRS.fdNIM.setText(tblCariMK.getValueAt(row, 0).toString());
            EntriKRS.fdNama.setText(tblCariMK.getValueAt(row, 1).toString());
            EntriKRS.fdSemester.setText(tblCariMK.getValueAt(row, 2).toString());
        } else if (LHS.fieldNIM != null || LHS.fieldNama != null || LHS.fieldSemester != null) {
            LHS.fieldNIM.setText(tblCariMK.getValueAt(row, 0).toString());
            LHS.fieldNama.setText(tblCariMK.getValueAt(row, 1).toString());
            LHS.fieldSemester.setText(tblCariMK.getValueAt(row, 2).toString());
        } else if (EntriNilai.fieldNIM != null || EntriNilai.fieldNama != null || EntriNilai.fieldSemester != null) {
            EntriNilai.fieldNIM.setText(tblCariMK.getValueAt(row, 0).toString());
            EntriNilai.fieldNama.setText(tblCariMK.getValueAt(row, 1).toString());
            EntriNilai.fieldSemester.setText(tblCariMK.getValueAt(row, 2).toString());
        } else if (EntriNilaiPerMataKuliah.fieldNIM != null
                || EntriNilaiPerMataKuliah.fieldNama != null
                || EntriNilaiPerMataKuliah.fieldSemester != null) {
            EntriNilaiPerMataKuliah.fieldNIM.setText(tblCariMK.getValueAt(row, 0).toString());
            EntriNilaiPerMataKuliah.fieldNama.setText(tblCariMK.getValueAt(row, 1).toString());
            EntriNilaiPerMataKuliah.fieldSemester.setText(tblCariMK.getValueAt(row, 2).toString());
        }
        this.dispose();
        }
    
    private void tblCariMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCariMKMouseClicked
        // TODO add your handling code here:
        tblCariMKMouseClicked1();
    }//GEN-LAST:event_tblCariMKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CariMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CariMHS().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JTextField fdCariMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCariMK;
    // End of variables declaration//GEN-END:variables
}
