/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Akademik;

/**
 *
 * @author 3cc
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuMHS = new javax.swing.JMenuItem();
        menuMK = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        entriKRS = new javax.swing.JMenuItem();
        entriNilai = new javax.swing.JMenuItem();
        cetak = new javax.swing.JMenu();
        menuLmk = new javax.swing.JMenuItem();
        menuLmhs = new javax.swing.JMenuItem();
        menuLn = new javax.swing.JMenuItem();
        menuLHS = new javax.swing.JMenuItem();
        setting = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        menuLO1 = new javax.swing.JMenuItem();
        menuLO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MENU"); // NOI18N

        jMenu1.setText("File");

        menuMHS.setText("Mahasiswa");
        menuMHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMHSActionPerformed(evt);
            }
        });
        jMenu1.add(menuMHS);

        menuMK.setText("Mata Kuliah");
        menuMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMKActionPerformed(evt);
            }
        });
        jMenu1.add(menuMK);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Entri");

        entriKRS.setText("Entri KRS");
        entriKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entriKRSActionPerformed(evt);
            }
        });
        jMenu2.add(entriKRS);

        entriNilai.setText("Entri Nilai");
        entriNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entriNilaiActionPerformed(evt);
            }
        });
        jMenu2.add(entriNilai);

        jMenuBar1.add(jMenu2);

        cetak.setText("Cetak");

        menuLmk.setText("Laporan Mata Kuliah");
        menuLmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLmkActionPerformed(evt);
            }
        });
        cetak.add(menuLmk);

        menuLmhs.setText("Laporan Mahasiswa");
        menuLmhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLmhsActionPerformed(evt);
            }
        });
        cetak.add(menuLmhs);

        menuLn.setText("Laporan Nilai");
        menuLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLnActionPerformed(evt);
            }
        });
        cetak.add(menuLn);

        menuLHS.setText("Lembar Hasil Studi");
        menuLHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLHSActionPerformed(evt);
            }
        });
        cetak.add(menuLHS);

        jMenuBar1.add(cetak);

        setting.setText("Pengaturan");

        menuUser.setText("Pengguna");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        setting.add(menuUser);

        menuLO1.setText("Ganti Password");
        menuLO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLO1ActionPerformed(evt);
            }
        });
        setting.add(menuLO1);

        menuLO.setText("Logout");
        menuLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLOActionPerformed(evt);
            }
        });
        setting.add(menuLO);

        jMenuBar1.add(setting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entriKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entriKRSActionPerformed
        // TODO add your handling code here:
        new EntriKRS().show();
        //this.dispose();
    }//GEN-LAST:event_entriKRSActionPerformed

    private void entriNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entriNilaiActionPerformed
        // TODO add your handling code here:
        new EntriNilaiPerMataKuliah().show();
        //this.dispose();
    }//GEN-LAST:event_entriNilaiActionPerformed

    private void menuLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLnActionPerformed
        // TODO add your handling code here:
        new CetakLaporanNilai().show();
        //this.dispose();
    }//GEN-LAST:event_menuLnActionPerformed

    private void menuMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMKActionPerformed
        // TODO add your handling code here:
        new MataKuliah().show();
        //this.dispose();
    }//GEN-LAST:event_menuMKActionPerformed

    private void menuLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLOActionPerformed
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_menuLOActionPerformed

    private void menuMHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMHSActionPerformed
        // TODO add your handling code here:
        new Mahasiswa().show();
        //this.dispose();
    }//GEN-LAST:event_menuMHSActionPerformed

    private void menuLO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLO1ActionPerformed
        // TODO add your handling code here:
        new GantiPassword().show();
        this.dispose();
    }//GEN-LAST:event_menuLO1ActionPerformed

    private void menuLmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLmkActionPerformed
        // TODO add your handling code here:
        new LaporanMataKuliah().printPDF();
        //this.dispose();
    }//GEN-LAST:event_menuLmkActionPerformed

    private void menuLmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLmhsActionPerformed
        // TODO add your handling code here:
        new LaporanMahasiswa().printPDF();
    }//GEN-LAST:event_menuLmhsActionPerformed

    private void menuLHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLHSActionPerformed
        // TODO add your handling code here:
        new LHS().show();
        //this.dispose();
    }//GEN-LAST:event_menuLHSActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cetak;
    private javax.swing.JMenuItem entriKRS;
    private javax.swing.JMenuItem entriNilai;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuLHS;
    private javax.swing.JMenuItem menuLO;
    private javax.swing.JMenuItem menuLO1;
    private javax.swing.JMenuItem menuLmhs;
    private javax.swing.JMenuItem menuLmk;
    private javax.swing.JMenuItem menuLn;
    private javax.swing.JMenuItem menuMHS;
    private javax.swing.JMenuItem menuMK;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JMenu setting;
    // End of variables declaration//GEN-END:variables
}
