/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum9_16;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.sql.Date; 
import java.util.Calendar;
/**
 *
 * @author 3cc
 */
public class PinjamMobil extends javax.swing.JFrame {

    public Connection koneksi = null;
    public Statement kn =  null;
    public ResultSet rs = null;
    /**
     * Creates new form PinjamMobil
     */
    public PinjamMobil() {
        initComponents();
        kotakKombo();
        koneksii();
        tampil();
        
        UIManager.put("OptionPane.okButtonText", "Okeh");
        
        buttonKeluar.addActionListener((ActionEvent e) -> {
            WindowEvent windowEvent = new WindowEvent(PinjamMobil.this, WindowEvent.WINDOW_CLOSING);
            formWindowClosing(windowEvent);
        });
        
        this.addWindowListener(new WindowAdapter() {
            /*public void tutupJendela(WindowEvent evt) {
                formWindowClosing(evt);
            }
            
            public void sudahTutup (WindowEvent evt) {
                formWindowClosed(evt);
            }*/
        });
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldNoPinjam = new javax.swing.JTextField();
        fieldTotalBayar = new javax.swing.JTextField();
        fieldNamaPeminjam = new javax.swing.JTextField();
        fieldSewa = new javax.swing.JTextField();
        fieldNoPolisi = new javax.swing.JTextField();
        fieldLamaPinjam = new javax.swing.JTextField();
        fieldCariNoPinjam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tanggalPinjam = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        opsiJenisMobil = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        buttonSimpan = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonTabel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("No Pinjam");

        jLabel2.setText("No Polisi");

        jLabel4.setText("Tanggal Pinjam");

        jLabel7.setText("Total Bayar");

        jLabel8.setText("Cari No. Pinjam");

        fieldNoPinjam.setName("Nomor Pinjaman"); // NOI18N
        fieldNoPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNoPinjamActionPerformed(evt);
            }
        });

        fieldTotalBayar.setEditable(false);
        fieldTotalBayar.setName("Total Bayar"); // NOI18N
        fieldTotalBayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldTotalBayarMouseClicked(evt);
            }
        });
        fieldTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalBayarActionPerformed(evt);
            }
        });

        fieldNamaPeminjam.setName("Nama Peminjam"); // NOI18N

        fieldSewa.setName("Sewa / Hari"); // NOI18N

        fieldNoPolisi.setName("Nomor Polisi"); // NOI18N

        fieldLamaPinjam.setName("Lama Pinjam"); // NOI18N
        fieldLamaPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLamaPinjamActionPerformed(evt);
            }
        });

        fieldCariNoPinjam.setName("Cari Nomor Pinjaman"); // NOI18N
        fieldCariNoPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCariNoPinjamActionPerformed(evt);
            }
        });

        jLabel9.setText("Hari");

        jLabel3.setText("Nama Peminjam");

        tanggalPinjam.setDateFormatString("yyyy-MM-dd");
        tanggalPinjam.setName("Tanggal Pinjam"); // NOI18N

        jLabel5.setText("Lama Pinjam");

        jLabel6.setText("Sewa/hari");

        opsiJenisMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        opsiJenisMobil.setName("Jenis Mobil"); // NOI18N
        opsiJenisMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsiJenisMobilActionPerformed(evt);
            }
        });

        jLabel10.setText("Jenis Mobil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCariNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fieldLamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opsiJenisMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tanggalPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opsiJenisMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldLamaPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCariNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonUpdate.setText("UPDATE");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonHapus.setText("HAPUS");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonKeluar.setText("KELUAR");

        buttonReset.setText("RESET");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonTabel.setText("EDIT TABEL");
        buttonTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonHapus)
                    .addComponent(buttonKeluar)
                    .addComponent(buttonReset)
                    .addComponent(buttonTabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(buttonTabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(buttonReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonKeluar))
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kotakKombo(){
    // Daftar item dalam array
    String[] jenisMobill = {"", "Afanja", "Alfard", "Perari", "Senia", "Inofa", "Kunkun"};
    
    // Membuat model baru dengan array item
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(jenisMobill);
    
    // Menetapkan model ke JComboBox
    opsiJenisMobil.setModel(model);
    }


    private boolean cekNoPinjam(String noPinjam){
        boolean duplikat = false;
        
        try{
            String kueri = "select count(*) from pinjammobil where noPinjam = ?";
            try (PreparedStatement ns = koneksi.prepareStatement(kueri)) {
                ns.setString(1, noPinjam);
                rs = ns.executeQuery();
                
                if(rs.next()){
                    int hitung = rs.getInt(1);
                    if(hitung > 0){
                        duplikat = true;
                    }
                }
            }
        }catch(SQLException e){
            /*JOptionPane.showMessageDialog(null, "Field " + field.getName() + 
                    " tidak boleh kurang dari satu!", 
                    "input tidak valid!", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memeriksa duplikat:\n"
                            + e.getMessage(), "Masalah Pemeriksaan Duplikat", JOptionPane.ERROR_MESSAGE);
        }
        return duplikat;
    }
    private void koneksii() {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            koneksi = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/oop3genap","root","");
            kn = koneksi.createStatement();
            System.out.println("Koneksi dan statement berhasil dibuat!");
        }catch(SQLException e){
            /*JOptionPane.showMessageDialog(null, "Field " + field.getName() + 
                    " tidak boleh kurang dari satu!", 
                    "input tidak valid!", JOptionPane.ERROR_MESSAGE);*/
            JOptionPane.showMessageDialog(null, "Kesalahan koneksi atau pembuatan statement\n" + e.getMessage(),
                                            "Masalah Koneksi-Statement", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Kesalahan penggunaan driver\n" + e.getMessage(),
                                            "Masalah Driver", JOptionPane.ERROR_MESSAGE);
            System.exit(0); //harusnya nilainya 1
        }   
    }
    
    Object[] dariDataa;
    String noPinjam;
    Date tglPinjam;
    String namaPeminjam;
    String jenisMobil;
    int sewaPerhari;
    String noPolisi;
    int lamaPinjamm;
    String totalBayarr;
    // Array untuk menentukan kolom mana yang tidak bisa diedit
    boolean canEdit[] = new boolean[]{
        false, false, false, false, false, false, false, false}; // Semua kolom tidak bisa diedit
    
    private void tampil(){
        // Membuat objek Calendar dan mengatur tanggal
        Calendar calendar = Calendar.getInstance();
        calendar.set(2024, Calendar.DECEMBER, 1); // Tahun 2024, Desember (bulan ke-11)
        java.util.Date tglPinjamm = calendar.getTime();
        tanggalPinjam.setDate(tglPinjamm);
        // Override isCellEditable untuk mengembalikan nilai yang sesuai dari array canEdit
    DefaultTableModel tebelData = new DefaultTableModel() {
    @Override
    public boolean isCellEditable(int row, int column) {
        return canEdit[column];  // Menentukan kolom mana yang bisa diedit (false = tidak bisa diedit)
    }
    };
        tebelData.addColumn("No Pinjaman");
        tebelData.addColumn("Tgl Pinjam");
        tebelData.addColumn("Nama Peminjam");
        tebelData.addColumn("Jenis Mobil");
        tebelData.addColumn("Sewa/Hari");
        tebelData.addColumn("No Polisi");
        tebelData.addColumn("Lama Pinjam");
        tebelData.addColumn("Total Bayar");
        
        try{
            koneksii();
            buttonUpdate.setEnabled(false);
            buttonHapus.setEnabled(false);
            String sql = "Select * from pinjammobil";
            rs = kn.executeQuery(sql);
            
            while(rs.next()){
                tebelData.addRow(new Object[]{
                    rs.getString(1),
                    rs.getDate(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getInt(5),
                    rs.getString(6),
                    rs.getInt(7),
                    rs.getString(8)
                });
            }
            tabel.setModel(tebelData);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan" + e);
        }
    }
    /*String jenisMobil = (String) opsiJenisMobil.getSelectedItem();
if (jenisMobil != null) {
    stmt.setString(3, jenisMobil);
} else {
    stmt.setNull(3, java.sql.Types.VARCHAR); // Menangani null jika tidak ada pilihan
}
*/
    private Object[] dariData() {
        return new Object[]{
            fieldNoPinjam.getText().trim(),
            ((JTextField)tanggalPinjam.getDateEditor().getUiComponent()).getText(),
            fieldNamaPeminjam.getText().trim(),
            opsiJenisMobil.getSelectedItem(),
            fieldSewa.getText().trim(),
            fieldNoPolisi.getText().trim(),
            fieldLamaPinjam.getText().trim(),
            fieldTotalBayar.getText().trim()
        };
    }
    
    private void hapusField() {
        fieldNoPinjam.setText("");
        tanggalPinjam.setDateFormatString("");
        fieldNamaPeminjam.setText("");
        opsiJenisMobil.setSelectedItem("");
        fieldSewa.setText("");
        fieldNoPolisi.setText("");
        fieldLamaPinjam.setText("");
        fieldTotalBayar.setText("");
        fieldCariNoPinjam.setText("");
    }
    
    private boolean validasiField(JTextField field) {
    if (field.getText() == null) {
        JOptionPane.showMessageDialog(null, "Field " + field.getName() + " tidak boleh kosong!", 
                "Masalah Input", JOptionPane.ERROR_MESSAGE);
        return false;  // Jika field null, langsung kembalikan false
    }
    
    // Cek apakah field kosong atau hanya berisi spasi
    if (field.getText().trim().isBlank()) {
        JOptionPane.showMessageDialog(null, "Field " + field.getName() + " tidak boleh kosong!", 
                "Masalah Input", JOptionPane.ERROR_MESSAGE);
        return false;  // Jika kosong, kembalikan false
    }
    
    return true;  // Field valid, kembalikan true
}

    
    private boolean validasiInput(JTextField field) {
    // Ambil teks dari field dan hilangkan spasi di kedua ujungnya
    String input = field.getText().trim();

    // Cek jika input kosong
    if (input.isEmpty() || "".equals(input)) {
        JOptionPane.showMessageDialog(null, "Field " + field.getName() + " tidak boleh kosong!",
                "Input tidak valid!", JOptionPane.ERROR_MESSAGE);
        return false;  // Jika kosong, kembalikan false
    }

    // Cek apakah input berupa angka bulat (integer)
    try {
        int angka = Integer.parseInt(input);  // Coba konversi input ke Integer
        // Cek apakah angka negatif
        if (angka < 0) {
            JOptionPane.showMessageDialog(null, "Field " + field.getName() + " tidak boleh negatif!",
                    "Input tidak valid!", JOptionPane.ERROR_MESSAGE);
            return false;  // Jika angka negatif, kembalikan false
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Field " + field.getName() + " harus berupa angka bulat (integer)!",
                "Input tidak valid!", JOptionPane.ERROR_MESSAGE);
        return false;  // Jika gagal konversi, berarti input bukan angka
    }

    return true;  // Input valid
}
    
    private boolean validasiTanggal(com.toedter.calendar.JDateChooser pilihTanggal){
        if (pilihTanggal.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Harap pilih tanggal\n",
                                            "Masalah Pemilihan Tanggal", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private boolean validasiKombo(javax.swing.JComboBox pilihJenis){
        if (pilihJenis.getSelectedItem() == "") {
            JOptionPane.showMessageDialog(null, "Harap pilih jenis mobil\n",
                                            "Masalah Pemilihan Mobil", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    void eventHapus(){
        try{
            koneksii();
            String sql = "delete from pinjammobil where noPinjam = '"+fieldNoPinjam.getText()+"'";
            kn.executeUpdate(sql);
            tampil();
            hapusField();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            buttonSimpan.setEnabled(true);
            koneksi.close();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Kesalahan penghapusan data\n" + e.getMessage(),
                                            "Masalah Penghapusan Data", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void eventUpah(){
        if (!validasiInput(fieldSewa) 
                || !validasiInput(fieldLamaPinjam)) 
        {return;}
        
        double totalBayar;
        try {
            double sewa = Double.parseDouble(fieldSewa.getText());
            double lamaPinjam = Double.parseDouble(fieldLamaPinjam.getText());

            totalBayar = sewa * lamaPinjam;
            fieldTotalBayar.setText(String.valueOf(totalBayar));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input tidak valid, pastikan semua kolom berisi angka.",
            "Kesalahan Format Angka", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void eventSimpan(){
        koneksii();
        if ( !validasiField(fieldNoPinjam) || !validasiField(fieldNamaPeminjam) 
              || !validasiField(fieldNoPolisi) || !validasiTanggal(tanggalPinjam)
                || !validasiKombo(opsiJenisMobil)) 
        {return;}
        
        dariDataa = dariData();
        noPinjam = (String) dariDataa[0];
        tglPinjam = Date.valueOf((String) dariDataa[1]);
        namaPeminjam = (String) dariDataa[2];
        jenisMobil = (String) dariDataa[3];
        sewaPerhari = Integer.parseInt((String) dariDataa[4]);
        noPolisi = (String) dariDataa[5];
        lamaPinjamm = Integer.parseInt((String) dariDataa[6]);
        totalBayarr = (String) dariDataa[7];
        
        // Memeriksa apakah nomor slip sudah ada
        if (cekNoPinjam(noPinjam)){
        JOptionPane.showMessageDialog(null, "Nomor Peminjaman sudah ada di database, ganti yang lain" ,
                "Masalah Duplikasi", JOptionPane.ERROR_MESSAGE);
        return;  // keluar jika duplikasi ditemukan
        }
    
        String kueri = "insert into pinjammobil (noPinjam, tanggalPinjam, namaPeminjam, jenisMobil,"
            + "sewaPerhari, noPolisi, lamaPinjam, totalBayar)"
            + " values (?, ?, ?, ?, ?, ?, ?, ?)";
    
    try (PreparedStatement stmt = koneksi.prepareStatement(kueri)) {
        // Menyiapkan data untuk disimpan
        stmt.setString(1, noPinjam);
        // bikin objek modal objek awokaowkaowak
        stmt.setDate(2, tglPinjam );
        //stmt.setInt(3, Integer.parseInt((String) dariDataa[2]));
        stmt.setString(3, namaPeminjam );
        stmt.setString(4, jenisMobil );
        stmt.setInt(5, sewaPerhari);
        stmt.setString(6, noPolisi );
        stmt.setInt(7, lamaPinjamm);
        stmt.setString(8, totalBayarr);

        // Eksekusi perintah SQL
        int barisEdit = stmt.executeUpdate();
        if (barisEdit > 0) {
            tampil();
            hapusField();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        }   
    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(null, "Proses penyimpanan gagal\n" + e,
                "Masalah Penyimpanan", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (koneksi != null && !koneksi.isClosed()) {
                koneksi.close();
            }
        } catch (SQLException e) {
        }
    }
    }
    
    void eventSimpann(){
        eventUpah();
        eventSimpan();
    }
    
    void eventUpdatee(){
        eventUpah();
        eventUpdate();
    }
    void eventUpdate(){
        koneksii();
        if ( !validasiField(fieldNoPinjam) || !validasiField(fieldNamaPeminjam) 
              || !validasiField(fieldNoPolisi) || !validasiTanggal(tanggalPinjam)
                || !validasiKombo(opsiJenisMobil)) 
        {return;}
        
        dariDataa = dariData();
        noPinjam = (String) dariDataa[0];
        tglPinjam = Date.valueOf((String) dariDataa[1]);
        namaPeminjam = (String) dariDataa[2];
        jenisMobil = (String) dariDataa[3];
        sewaPerhari = Integer.parseInt((String) dariDataa[4]);
        noPolisi = (String) dariDataa[5];
        lamaPinjamm = Integer.parseInt((String) dariDataa[6]);
        totalBayarr = (String) dariDataa[7];
        
        String kueri = "update pinjammobil set tanggalPinjam = ?, "
                + " namaPeminjam = ?, jenisMobil = ?, sewaPerhari = ?,"
                + "noPolisi = ?, lamaPinjam = ?, totalBayar = ? where noPinjam = ?";
        try(PreparedStatement stmt = koneksi.prepareStatement(kueri)){
        
        
            stmt.setDate(1, tglPinjam);
            stmt.setString(2, namaPeminjam);
            stmt.setString(3, jenisMobil);
            stmt.setInt(4, sewaPerhari);
            stmt.setString(5, noPolisi);
            stmt.setInt(6, lamaPinjamm);
            stmt.setString(7, totalBayarr);
            stmt.setString(8, noPinjam);
            
            int barisEdit = stmt.executeUpdate();
            if (barisEdit > 0) {
            tampil();
            hapusField();
            buttonSimpan.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
            koneksi.close();
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Proses Update Gagal\n" + e,
                "Masalah Update", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /*void eventTabell(java.awt.event.MouseEvent evt){
        JOptionPane.showMessageDialog(
                null, """
                        Cara Update: Cari Nomor Pinjaman, 
                        Input di kolom No Pinjaman""",
                "Peringatan", JOptionPane.ERROR_MESSAGE);
    }*/
    
    void eventTabel(java.awt.event.MouseEvent evt){
        hapusField();
        if(evt.getClickCount()==1){
        int baris = tabel.getSelectedRow();
        fieldNoPinjam.setText(tabel.getValueAt(baris, 0).toString());
        buttonSimpan.setEnabled(false);
        buttonUpdate.setEnabled(true);
        buttonHapus.setEnabled(true);
        }
    }
    
    /*void eventNoPinjamm(){
        try{
            koneksii();
            String sql = "Select * from pinjammobil where nopinjam='" + String.valueOf(fieldNoPinjam.getText()) +"'";
            rs = kn.executeQuery(sql);
            if (rs.next())
            {
            fieldNoPinjam.setText(rs.getString(1));
            
            java.sql.Date sqlDate = rs.getDate(2);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(sqlDate);
            java.util.Date utilDate = calendar.getTime();
            tanggalPinjam.setDate(utilDate);
            
            fieldNamaPeminjam.setText(rs.getString(3));
            opsiJenisMobil.setSelectedItem(rs.getString(4));
            fieldSewa.setText(rs.getString(5));
            fieldNoPolisi.setText(rs.getString(6));
            fieldLamaPinjam.setText(rs.getString(7));
            fieldTotalBayar.setText(rs.getString(8));
            }else{
            }
            } catch (SQLException e){
            JOptionPane.showMessageDialog(null,"Terjadi Kesalahan " + e);
            }
    }*/
    
    void eventSebelumTutup(java.awt.event.WindowEvent evt){
        Object[] pilhans = {"Ya, Keluar", "Tak, masih pakai"};
        
        int pilihan1; 
        pilihan1 = JOptionPane.showOptionDialog(null, 
                "Anda ingin keluar?",
                "Konfirmasi Keluar", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, pilhans, pilhans[1]);
        if (pilihan1 == JOptionPane.YES_OPTION) {
            dispose();
        } else if (pilihan1 == JOptionPane.NO_OPTION) {
            evt.getWindow().setVisible(true);
        }
    }
    
    void eventSetelahTutup(){
        JOptionPane.showMessageDialog(null, 
                "Terima Kasih telah menggunakan aplikasi", 
                "Aplikasi Ditutup", JOptionPane.PLAIN_MESSAGE);
    }
    
    void eventBuka(){
        JOptionPane.showMessageDialog(null,
                """
                Selamat menggunakan aplikasi!
                Anda bisa estimasikan total bayar
                Cara Update: Cari Nomor Pinjaman, 
                Input di kolom No Pinjaman
                tanpa menyimpan atau menghapus.
                Lengkapi data!
                Edit data atau cari data,
                Lakukan satu-satu!
                Jangan mengedit total!
                JANGAN KORUPSI!
                """, 
        "Membuka Aplikasi", JOptionPane.INFORMATION_MESSAGE);
    }
    
    void cariNoPinjam(){
        // Override isCellEditable untuk mengembalikan nilai yang sesuai dari array canEdit
        DefaultTableModel tebelCari = new DefaultTableModel() {
    @Override
    public boolean isCellEditable(int row, int column) {
        return canEdit[column];  // Menentukan kolom mana yang bisa diedit (false = tidak bisa diedit)
    }
    };
        tebelCari.addColumn("NO PINJAMAN");
        tebelCari.addColumn("TGL PINJAM");
        tebelCari.addColumn("NAMA PEMINJAM");
        tebelCari.addColumn("JENIS MOBIL");
        tebelCari.addColumn("SEWA / HARI");
        tebelCari.addColumn("NO POLISI");
        tebelCari.addColumn("LAMA PINJAM");
        tebelCari.addColumn("TOTAL BAYAR");
        
        try{
            koneksii();
            String sql = "Select * from pinjammobil where noPinjam like '%"+ fieldCariNoPinjam.getText() +"%'";
            rs = kn.executeQuery(sql);
            
            while(rs.next()){
                tebelCari.addRow(new Object[]{
                    rs.getString(1),
                    rs.getDate(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getInt(5),
                    rs.getString(6),
                    rs.getInt(7),
                    rs.getString(8)
                });
            }
            hapusField();
            tabel.setModel(tebelCari);
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan " + e);
        }
    }
    
    void eventTotal(){
        JOptionPane.showMessageDialog(null, "Tidak dapat mengedit total!",
                "Peringatan", JOptionPane.ERROR_MESSAGE);
    }
    
    void klikTotal(java.awt.event.MouseEvent evt){
        if (evt.getClickCount() == 1) {
            JOptionPane.showMessageDialog(null, "Tidak dapat mengedit total!", "Peringatan", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void reset(){
        hapusField();
        tampil();
        buttonSimpan.setEnabled(true);
    }
    
    void eventNoPinjam(){
        try{
            koneksii();
            String sql = "Select * from pinjammobil where nopinjam='" + String.valueOf(fieldNoPinjam.getText()) +"'";
            rs = kn.executeQuery(sql);
            if (rs.next())
            {
            fieldNoPinjam.setText(rs.getString(1));
            tanggalPinjam.setDate(rs.getDate(2));
            fieldNamaPeminjam.setText(rs.getString(3));
            opsiJenisMobil.setSelectedItem(rs.getString(4));
            fieldSewa.setText(rs.getString(5));
            fieldNoPolisi.setText(rs.getString(6));
            fieldLamaPinjam.setText(rs.getString(7));
            fieldTotalBayar.setText(rs.getString(8));
            }else{
            }
            } catch (SQLException e){
            JOptionPane.showMessageDialog(null,"Terjadi Kesalahan " + e);
            }
    }
    private void fieldTotalBayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldTotalBayarMouseClicked
        // TODO add your handling code here:
        klikTotal(evt);
    }//GEN-LAST:event_fieldTotalBayarMouseClicked

    private void fieldTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalBayarActionPerformed
        // TODO add your handling code here:
        eventTotal();
    }//GEN-LAST:event_fieldTotalBayarActionPerformed

    private void fieldLamaPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLamaPinjamActionPerformed
        // TODO add your handling code here:
        eventUpah();
    }//GEN-LAST:event_fieldLamaPinjamActionPerformed

    private void fieldCariNoPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCariNoPinjamActionPerformed
        // TODO add your handling code here:
        cariNoPinjam();
    }//GEN-LAST:event_fieldCariNoPinjamActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        eventSimpann();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        eventUpdatee();
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        eventHapus();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        eventTabel(evt);
    }//GEN-LAST:event_tabelMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        eventSebelumTutup(evt);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        eventSetelahTutup();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        eventBuka();
    }//GEN-LAST:event_formWindowOpened

    private void fieldNoPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNoPinjamActionPerformed
        // TODO add your handling code here:
        buttonUpdate.setEnabled(true);
        buttonHapus.setEnabled(true);
        buttonSimpan.setEnabled(false);
        eventNoPinjam();
    }//GEN-LAST:event_fieldNoPinjamActionPerformed

    private void opsiJenisMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsiJenisMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opsiJenisMobilActionPerformed

    private void buttonTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTabelActionPerformed
        // TODO add your handling code here:
        eventNoPinjam();
    }//GEN-LAST:event_buttonTabelActionPerformed

    private void fieldNamaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaPeminjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinjamMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PinjamMobil().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonTabel;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTextField fieldCariNoPinjam;
    private javax.swing.JTextField fieldLamaPinjam;
    private javax.swing.JTextField fieldNamaPeminjam;
    private javax.swing.JTextField fieldNoPinjam;
    private javax.swing.JTextField fieldNoPolisi;
    private javax.swing.JTextField fieldSewa;
    private javax.swing.JTextField fieldTotalBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> opsiJenisMobil;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tanggalPinjam;
    // End of variables declaration//GEN-END:variables
}
